trigger:
- master
- develop
- feature/*
- release/*
- bugfix/*
- hotfix/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: FtpUpload@2
  displayName: 'Upload to webspace'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  inputs:
    credentialsOption: 'inputs'
    serverUrl: '***REMOVED***'
    username: '***REMOVED***'
    password: '***REMOVED***'
    rootDirectory: '$(System.DefaultWorkingDirectory)'
    filePatterns: '**'
    remoteDirectory: '/symphoniacus/'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: false
